feat: user register
felipegchi/Animulet pull request #2
Opened 2021-10-09 22:49 UTC by samueldurantes

2021-10-11 21:40 UTC, algebraic-dev requested changes

2021-10-11 21:40 UTC, algebraic-dev commented on src/modules/user/controllers/userController.ts
> +    console.log(user.left)
Remove console.log

2021-10-11 21:40 UTC, algebraic-dev commented on src/server.ts
>    app.use(userRoutes)
Add /auth in front of user routes.

2021-10-11 21:40 UTC, algebraic-dev commented on test/user/register.test.ts
> +      .then((response) => done(response))
You can apply eta reduction on .then and .catch. `a => b(a)` is equivalent to `b`

2021-10-11 22:03 UTC, samueldurantes commented
Done!

2021-10-12 00:10 UTC, algebraic-dev approved these changes

2021-10-12 00:10 UTC, merged